name: digital_turbine_task
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pandas==1.5.3
  - numpy==1.23.5
  - scikit-learn==1.3.0
  - plotly==5.16.0
  - catboost==1.2
  - pip:
    - ipykernel==6.25.1
    - nbformat==5.9.2
